### ISSUE TITLE
Roulette 1.20.1 no longer Works

### ISSUE THREAD

**Issue by Blueeyestar** [aematsubara/Roulette#29]
Unfortunately, roulette no longer works in 1.20.1. I would be happy if you take a look at the error.

Thank you for your good work

```


[01:41:01] [Server thread/INFO]: [Roulette] Enabling Roulette v1.9.5
[01:41:01] [Server thread/WARN]: java.lang.NoSuchFieldException: no such field: net.minecraft.server.level.EntityPlayer.b/net.minecraft.server.network.PlayerConnection/getField
[01:41:01] [Server thread/WARN]: 	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:917)
[01:41:01] [Server thread/WARN]: 	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:994)
[01:41:01] [Server thread/WARN]: 	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3655)
[01:41:01] [Server thread/WARN]: 	at java.base/java.lang.invoke.MethodHandles$Lookup.findGetter(MethodHandles.java:3033)
[01:41:01] [Server thread/WARN]: 	at Roulette_1.9.5.jar//me.matsubara.roulette.util.xseries.ReflectionUtils.<clinit>(ReflectionUtils.java:133)
[01:41:01] [Server thread/WARN]: 	at Roulette_1.9.5.jar//me.matsubara.roulette.RoulettePlugin.onEnable(RoulettePlugin.java:71)
[01:41:01] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[01:41:01] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[01:41:01] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[01:41:01] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[01:41:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:566)
[01:41:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:477)
[01:41:01] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[01:41:01] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435)
[01:41:01] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[01:41:01] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[01:41:01] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[01:41:01] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1623)
[01:41:01] [Server thread/WARN]: Caused by: java.lang.NoSuchFieldError: b
[01:41:01] [Server thread/WARN]: 	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
[01:41:01] [Server thread/WARN]: 	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962)
[01:41:01] [Server thread/WARN]: 	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:991)
[01:41:01] [Server thread/WARN]: 	... 16 more
```

**Comment by aematsubara** [comment]
Updated!
